### ISSUE TITLE
Wiki

### ISSUE THREAD

**Issue by alexjshepler** [Cenngo/R6Stats-Sharp#1]
Could you please give a wiki on this api please. It would be helpful because I'm trying to integrate this into my project and I'm finding that I'm having a hard time doing so

**Comment by Cenngo** [comment]
Currently working on the wiki and i will add some example code but since there are only a couple of methods probrably the main part you are having problems with is the object structrure, thats why on the next build i will add a docfx documentation to the repo. Which i hope will make finding the right data easier

**Comment by alexjshepler** [comment]
Thank you, is there an estimated time as of when this will be completed?

**Comment by Cenngo** [comment]
I am submitting the wiki entries as I go. And I am planning to push the DocFX documentation in a day or two.

**Comment by Cenngo** [comment]
wiki now has guides for the fundamental operations you can perform with the library and the reference documentation is now available under wiki/Data-Structure
